working_dir: /data/working_dirs
workflows_dirs: 
    - /home/joris/software/multiply-ui/multiply_ui/server/resources/workflows
scripts_dirs: 
    - /home/joris/software/multiply-ui/multiply_ui/server/resources/scripts
